name: changhongmenquan
on:
  workflow_dispatch:
  schedule:
    - cron: '57 0/6 * * *'

jobs:  # 623
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changhongmenquan
        env:
          je248: ${{ secrets.je248 }}
        run: |
          echo $je248 | jq -r .eckk43513 | /bin/bash
          echo $u4456 | jq -r .lur534 | /bin/bash
          echo $t8 | jq -r .z92982 | /bin/bash
          echo $lecx2 | jq -r .qe061 | /bin/bash
          echo $qtspc1 | jq -r .zmx378 | /bin/bash

